const BASE_API = '/admin'

//CONTROLLERS
const CONTROLLER_MEASUREMENT_SOURCES = `${BASE_API}/measurerment-sources`
const CONTROLLER_LABORATORIES = `${BASE_API}/laboratory`
const CONTROLLER_MEASUREMENT_SUBSOURCES = `${BASE_API}/measurerment-subsources`
const CONTROLLER_SOURCES_BY_SUBSOURCES = `${BASE_API}/sources-by-subsources`
const CONTROLLER_RESOLUTIONS = `${BASE_API}/Resolution`
const CONTROLLER_RESOLUTION_BY_SUBSOURCES = `${BASE_API}/resolution-by-subsources`
const CONTROLLER_NORMSECTORS=`${BASE_API}/normative-sector`
const CONTROLLER_RESOLUTIONS_BY_NORMSECTORS=`${BASE_API}/resolution-by-normative-sector`
const CONTROLLER_TYPE_ACTIVITY=`${BASE_API}/TypeActivity`
const CONTROLLER_TYPE_ACTIVITY_BY_NORMSECTORS=`${BASE_API}/type-activity-by-normative-sector`
const CONTROLLER_MEASUREMENT_PARAMETER = `${BASE_API}/measurement-parameter`

//RUTES COMPLETE
// TIPOS DE FUENTES DE MEDICIÓN
const GET_MEASUREMENT_SOURCES = `${CONTROLLER_MEASUREMENT_SOURCES}/get-measurerment-sources`
const POST_INSERT_OR_REPLACE_MEASUREMENT_SOURCES = `${CONTROLLER_MEASUREMENT_SOURCES}/insert-or-replace`

// LABORATORIOS
const GET_LABORATORIES = `${CONTROLLER_LABORATORIES}/get-laboratories-all`
const POST_SYNC_LABORATORIES = `${CONTROLLER_LABORATORIES}/sync-laboratories`

// TIPOS DE SUBFUENTES DE MEDICIÓN
const GET_MEASUREMENT_SUBSOURCES = `${CONTROLLER_MEASUREMENT_SUBSOURCES}/get-measurerment-subsources`
const POST_INSERT_OR_REPLACE_MEASUREMENT_SUBSOURCES = `${CONTROLLER_MEASUREMENT_SUBSOURCES}/insert-or-replace`
const GET_SOURCES_BY_SUBSOURCES = `${CONTROLLER_SOURCES_BY_SUBSOURCES}/get-sources-by-subsource`
const POST_INSERT_OR_REPLACE_SOURCES_BY_SUBSOURCES = `${CONTROLLER_SOURCES_BY_SUBSOURCES}/insert-or-replace`

// RESOLUCIONES
const GET_RESOLUTIONS = `${CONTROLLER_RESOLUTIONS}/get-resolutions`
const POST_INSERT_OR_REPLACE_RESOLUTIONS = `${CONTROLLER_RESOLUTIONS}/insert-or-replace`
// RESOLUCIONES POR SUBFUENTES
const GET_RESOLUTION_BY_SUBSOURCE = `${CONTROLLER_RESOLUTION_BY_SUBSOURCES}/get-measurerment-subsource-by-resolution`
const POST_INSERT_OR_REPLACE_RESOLUTION_BY_SUBSOURCES = `${CONTROLLER_RESOLUTION_BY_SUBSOURCES}/insert-or-replace`

//SECTORES NORMATIVOS
const GET_NORMSECTORS = `${CONTROLLER_NORMSECTORS}/get-normative-sectors`
const POST_INSERT_OR_REPLACE_NORMSECTORS = `${CONTROLLER_NORMSECTORS}/insert-or-replace`

//SECTORES NORMATIVOS POR RESOLUCIONES
const GET_RESOLUTIONS_BY_NORMSECTORS = `${CONTROLLER_RESOLUTIONS_BY_NORMSECTORS}/get-resolution-by-normative-sector`
const POST_INSERT_OR_REPLACE_RESOLUTIONS_BY_NORMSECTORS = `${CONTROLLER_RESOLUTIONS_BY_NORMSECTORS}/insert-or-replace`

//TIPO ACTIVIDAD
const GET_TYPE_ACTIVITY = `${CONTROLLER_TYPE_ACTIVITY}/get-type-activity`
const POST_INSERT_OR_REPLACE_TYPE_ACTIVITY = `${CONTROLLER_TYPE_ACTIVITY}/insert-or-replace`

//TIPO ACTIVIDAD POR SECTORES NORMATIVOS
const GET_TYPE_ACTIVITY_BY_NORMSECTORS = `${CONTROLLER_TYPE_ACTIVITY_BY_NORMSECTORS}/get-type-activity-by-normative-sector`
const POST_INSERT_OR_REPLACE_TYPE_ACTIVITY_BY_NORMSECTORS = `${CONTROLLER_TYPE_ACTIVITY_BY_NORMSECTORS}/insert-or-replace`

// PARÁMETROS DE MEDICIÓN
const GET_MEASUREMENT_PARAMETERS = `${CONTROLLER_MEASUREMENT_PARAMETER}/get-measurement-parameter`
const POST_INSERT_OR_REPLACE_MEASUREMENT_PARAMETER = `${CONTROLLER_MEASUREMENT_PARAMETER}/insert-or-replace`
export {
    GET_MEASUREMENT_SOURCES,
    POST_INSERT_OR_REPLACE_MEASUREMENT_SOURCES,
    GET_LABORATORIES,
    POST_SYNC_LABORATORIES,
    GET_MEASUREMENT_SUBSOURCES,
    POST_INSERT_OR_REPLACE_MEASUREMENT_SUBSOURCES,
    GET_SOURCES_BY_SUBSOURCES,
    POST_INSERT_OR_REPLACE_SOURCES_BY_SUBSOURCES,
    GET_RESOLUTIONS,
    POST_INSERT_OR_REPLACE_RESOLUTIONS,
    GET_RESOLUTION_BY_SUBSOURCE,
    POST_INSERT_OR_REPLACE_RESOLUTION_BY_SUBSOURCES,
    GET_NORMSECTORS,
    POST_INSERT_OR_REPLACE_NORMSECTORS,
    GET_RESOLUTIONS_BY_NORMSECTORS,
    POST_INSERT_OR_REPLACE_RESOLUTIONS_BY_NORMSECTORS,
    GET_TYPE_ACTIVITY,
    POST_INSERT_OR_REPLACE_TYPE_ACTIVITY,
    GET_TYPE_ACTIVITY_BY_NORMSECTORS,
    POST_INSERT_OR_REPLACE_TYPE_ACTIVITY_BY_NORMSECTORS,
    GET_MEASUREMENT_PARAMETERS,
    POST_INSERT_OR_REPLACE_MEASUREMENT_PARAMETER,
}
