// DestinationController: /api/destinations/**
const CONTROLLER_DESTINATIONS = '/destinations'

const GET_DESTINATIONS = CONTROLLER_DESTINATIONS
const POST_DESTINATION = CONTROLLER_DESTINATIONS
const PATCH_TOGGLE_DESTINATION = (id: number): string => `${CONTROLLER_DESTINATIONS}/${id}/toggle`

export { GET_DESTINATIONS, POST_DESTINATION, PATCH_TOGGLE_DESTINATION }
